### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by chointer** [chointer/RL_gait#1]
### **GitHub**
  - [ ] README.md 작성하기

### **Unity**
  - [x] 로봇 모델링
  - [x] 로봇 제어 스크립트
  - [ ] ML-Agents 환경 구성; #2

### **Python**
  - [ ] 학습 코드 작성
  - [ ] 딥러닝 모델 작성
  - [ ] 학습
