### ISSUE TITLE
TODO: ML-Agents 환경 구성

### ISSUE THREAD

**Issue by chointer** [chointer/RL_gait#2]
ML-Agents 함수를 이용해 state, reward, action 등을 구성한다.

### 1. Action [Done]
In `OnActionReceived`, `actions`를 받고, `RobotController.RotateAll`의 입력으로 넣어서 제어한다.  

### 2. State (Observation) [Done]
258cc6ba32867be81659d0dd83d5f1331fc885cf

- [x] **관절 각도**: 원하는 각도로 제어하려면 필요할 것 같다.
- [x] **관절 각속도**
- [ ] ~~**받고있는 힘**: 균형을 유지하기 위해서 필요할 것 같다.~~; 
함수를 찾지 못 함. 대신, 여러 step의 상태를 입력해서 힘 정보를 전달하고자 한다.
- [x] **지면 접촉 여부** (or 수직항력?): 균형을 유지하고, 보행할 때 필요할 것 같다.
- [x] **중력 방향**

### 3. Reward [Done]
d5aa3a05e8ceb74e9f2d332ac20e4871feec392e
- [x] **Goal**: goal 도달시 보상 (1) & `EndEpisode`
- [x] **Distance**: goal과 가까워지면 보상, 멀어지면 페널티, 너무 멀어지면 페널티 & `EndEpisode`
- [x] **Grounded**: 발이 아닌 부품이 지면과 접촉 시 페널티 (접촉 부품 개수 비례)

### 4. Functions
- [ ] `Initialize`
- [x] `CollectObservations`
- [x] `OnActionReceived`
- [x] `Heuristic`
- [x] Decision Requester (component)
